import 'package:audioplayers/audioplayers.dart';

/// Plays a short piano-like sample for each key in the on-screen keyboard.
/// Uses a small pool of low-latency players so fast runs and held chords can
/// sound polyphonically instead of cutting each other off.
class NotePlayer {
  /// Sample range, E1 to D#6. Wide enough for every note any drill can ask
  /// for: an Inversion Running cycle on B Major 7th reaches 94 at its apex,
  /// and the Voicings drill can transpose a full-width saved shape to 95.
  /// Both ran off the top of the old 48-77 set and fell silent. The low end
  /// is the guitar's low E. Pinned by test/note_range_test.dart; the samples
  /// are generated by `tool/gen_note_samples.py`.
  static const int lowMidi = 40;
  static const int highMidi = 95;

  static const int _poolSize = 10;

  final List<AudioPlayer> _pool = [
    for (var i = 0; i < _poolSize; i++)
      AudioPlayer()
        ..setPlayerMode(PlayerMode.lowLatency)
        ..setReleaseMode(ReleaseMode.stop),
  ];
  int _next = 0;

  /// Sound [midiNote]. Notes outside the sampled range are ignored (MIDI
  /// keyboards can send any pitch; we only ship samples for the app's range).
  void play(int midiNote) {
    if (midiNote < lowMidi || midiNote > highMidi) return;
    final player = _pool[_next];
    _next = (_next + 1) % _poolSize;
    player
      ..stop()
      ..play(AssetSource('audio/note_$midiNote.wav'));
  }

  void dispose() {
    for (final p in _pool) {
      p.dispose();
    }
  }
}
